apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-3d-tour-deployment
  namespace: tests
  labels:
    app: test-3d-tour
spec:
  replicas: 2
  selector:
    matchLabels:
      app: test-3d-tour
  template:
    metadata:
      labels:
        app: test-3d-tour
    spec:
      containers:
        - name: test-3d-tour-container
          image: registry.iteo.pro/3d-tour:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 400m
              memory: 512Mi
